{
    "name": "Partner Reseller Portal",
    "summary": "Authenticated reseller portal with reseller-scoped dashboard APIs.",
    "version": "19.0.1.0.0",
    "category": "Sales/CRM",
    "license": "LGPL-3",
    "author": "Do Nhat<donhat.hn@gmail.com>",
    "website": "https://github.com/donhat-dev/nakivo-test",
    "development_status": "Beta",
    "depends": [
        "nakivo_base_rest",
        "portal",
        "web",
        "crm",
        "sale_management",
        "account",
    ],
    "data": [
        "security/nakivo_reseller_portal_groups.xml",
        "security/ir.model.access.csv",
        "security/nakivo_reseller_portal_security.xml",
        "views/partner_views.xml",
        "views/crm_lead_views.xml",
        "views/sale_order_views.xml",
        "views/account_move_views.xml",
        "views/nakivo_reseller_portal_templates.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "nakivo_reseller_portal/static/src/partner_portal/partner_portal.scss",
            "nakivo_reseller_portal/static/src/partner_portal/components/app_sidebar.js",
            "nakivo_reseller_portal/static/src/partner_portal/components/app_sidebar.xml",
            "nakivo_reseller_portal/static/src/partner_portal/components/dashboard_view.js",
            "nakivo_reseller_portal/static/src/partner_portal/components/dashboard_view.xml",
            "nakivo_reseller_portal/static/src/partner_portal/components/delete_button.js",
            "nakivo_reseller_portal/static/src/partner_portal/components/delete_button.xml",
            "nakivo_reseller_portal/static/src/partner_portal/components/record_list_view.js",
            "nakivo_reseller_portal/static/src/partner_portal/components/record_list_view.xml",
            "nakivo_reseller_portal/static/src/partner_portal/components/create_opportunity_modal.js",
            "nakivo_reseller_portal/static/src/partner_portal/components/create_opportunity_modal.xml",
            "nakivo_reseller_portal/static/src/partner_portal/partner_portal.js",
            "nakivo_reseller_portal/static/src/partner_portal/partner_portal.xml",
        ],
    },
    "external_dependencies": {
        "python": ["pydantic"],
    },
    "installable": True,
    "application": True,
}
